# 内部转发请求配置，0值为无超时 单位为秒
# connTimeout: 用户连接超时
# idleConnTimeout: 空闲连接超时
# responseHeaderTimeout: 响应头超时
server-conn:
  connTimeout: 0
  idleConnTimeout: 0
  responseHeaderTimeout: 0

white-addr:
#  - '127.0.0.1'
#  - 'xxx.xxx.xxx.xxx'

# 开启特殊标记增强
flags: false

# 图片访问
domain: "http://127.0.0.1:8080"

# 内调llm，用于绘图时文本转tags
llm:
  base-url: "http://127.0.0.1:8081"
  model: "bing"
  token: "xxx"

# lmsys fn、 trigger，支持多模型参数映射，json格式
lmsys: |
  {
    "claude-3-5-sonnet-20240620": [ 70, 124 ]
  }

# hf 绘图接口配置化
# 若旧接口不可用，可以到huggingface上查找同类型的接口配置
# 参数替换：{{prompt}}、{{negative_prompt}}、{{sampler}}、{{style}}、{{seed}}
hf:
#  animagine-xl-3.1:
#    base-url: https://boboiazumi-animagine-xl-3-1.hf.space
#    fn: [5, 61]
#    data: '[
#      "{{prompt}}",
#      "{{negative_prompt}}",
#      {{seed}},
#      1024,
#      1024,
#      8,
#      35,
#      "{{sampler}}",
#      "1024 x 1024",
#      "{{style}}",
#      "Standard v3.1",
#      true,
#      0.55,
#      1.5,
#      false,
#      false,
#      null,
#      0.65
#    ]'
#  dalle-4k:
#    base-url: https://mukaist-dalle-4k.hf.space
#  dalle-3-xl:
#    base-url: https://ehristoforu-dalle-3-xl-lora-v2.hf.space

# gemini 自定义安全设置
google:
  tc: false # 是否使用提示词实现的toolCall
#  safes:
#    - category: HARM_CATEGORY_HARASSMENT
#      threshold: BLOCK_NONE

# cohere 自定义安全设置，目前仅兼容 Command R 08-2024、Command R+ 08-2024 及更新机型
cohere:
  safety: CONTEXTUAL # NONE | CONTEXTUAL | STRICT

bing:
  base-url: "https://edgeservices.bing.com/edgesvc"

claude:
  pad: 0
  cookies:
    - 'xxx1'
    - 'xxx2'

you:
  helper: 8082
  notice: "Creative Writing Mode"
  cookies:
    - 'xxx1'
    - 'xxx2'
browser-less:
  enabled: false
  disabled-gpu: true
  # 当无法找到指定的浏览器时可以在此配置路径
  # execPath: /usr/bin/microsoft-edge
  headless: new

# coze 默认配置；；；内置配置经常变动，难以维护改为配置化。新增webSdk模式，但还未得知速率是否有限制？？？
coze:
#  8k:
#    botId: 114514
#    version: 9527
#    scene: 2
#    isW: false
#  128k:
#    botId: 114514
#    version: 9527
#    scene: 2
#    isW: false
#  images:
#    botId: 114514
#    version: 9527
#    scene: 2

# 多个websdk账号可开启，用于请求计数，超过count数量该账号进入静置区
  websdk:
#    counter: 0
#    model:
#    accounts:
#    - email: xxx@gmail.com
#      password: xxx
#      validate: xxx@gmail.com

interpreter:
  base-url: http://127.0.0.1:8000
  echo-code: false
  ws: true

custom-llm:
  - base-url: http://127.0.0.1:8080/v1
    prefix: custom
    use-proxies: false
    tc: false

# toolCall 默认配置化; 在 flags 关闭时也可用
toolCall:
  id: -1
  enabled: false
  tasks: false

# 图片放大，domain需要公网可访问的地址
# key请到https://bigjpg.com获取，每月30次免费
# 目前注册没有限制，可配置多个key轮询
#magnify:
#  - "xxx"

# 用于处理llm响应时的内容
# find: 开头匹配
# end: 结束匹配
# content: 正则处理,用于正则替换。例如实现CoT内容屏蔽，达到类似openai_o1的效果
# desc: 可以在find命中时给前端反馈一些简单文字
#matcher:
#  - find: <!-- Attack
#    end: -->
#    content: "<!-- Attack [\\s\\S]+ -->:"
#  - find: <thinking>
#    end: </thinking>
#    content: "<thinking>[\\s\\S]+<\\/thinking>:thinking..."
#    desc: desc Response
